# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Titular', 'Titular'), ('Usuario', 'Usuario')], default='Titular', max_length=20),
        ),
    ]
