# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='line_of_business',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
