# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_company_line_of_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
