# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171017_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
